msx@server1:~$ python -m pip list
Package                   Version
------------------------- --------------------
addict                    2.4.0
alphashape                1.3.1
asttokens                 2.4.1
attrs                     24.2.0
backcall                  0.2.0
blinker                   1.8.2
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
click-log                 0.4.0
comm                      0.2.2
ConfigArgParse            1.7
contourpy                 1.1.1
cycler                    0.12.1
dash                      2.17.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
decorator                 5.1.1
executing                 2.0.1
fastjsonschema            2.20.0
filelock                  3.15.4
Flask                     3.0.3
fonttools                 4.53.1
fsspec                    2024.6.1
h5py                      3.11.0
idna                      3.8
importlib_metadata        8.4.0
importlib_resources       6.4.4
ipython                   8.12.3
ipywidgets                8.1.5
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_core              5.7.2
jupyterlab_widgets        3.0.13
kiwisolver                1.4.5
MarkupSafe                2.1.5
matplotlib                3.7.5
matplotlib-inline         0.1.7
mpmath                    1.3.0
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.1
nibabel                   5.2.1
numpy                     1.24.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.6.20
nvidia-nvtx-cu12          12.1.105
open3d                    0.18.0
packaging                 24.1
panda                     0.3.1
pandas                    2.0.3
parso                     0.8.4
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.4.0
pip                       24.2
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
plotly                    5.23.0
prompt_toolkit            3.0.47
ptyprocess                0.7.0
pure_eval                 0.2.3
Pygments                  2.18.0
pyntcloud                 0.3.1
pyparsing                 3.1.4
pyquaternion              0.9.9
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.2
referencing               0.35.1
requests                  2.32.3
retrying                  1.3.4
rpds-py                   0.20.0
Rtree                     1.3.0
scikit-learn              1.3.2
scipy                     1.10.1
setuptools                72.1.0
shapely                   2.0.6
six                       1.16.0
stack-data                0.6.3
sympy                     1.13.2
tenacity                  9.0.0
thop                      0.1.1.post2209072238
threadpoolctl             3.5.0
torch                     2.4.0
tqdm                      4.66.5
traitlets                 5.14.3
trimesh                   4.4.7
triton                    3.0.0
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
wcwidth                   0.2.13
Werkzeug                  3.0.4
wheel                     0.43.0
widgetsnbextension        4.0.13
zipp                      3.20.0
msx@server1:~$ conda list
# packages in environment:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
addict                    2.4.0                    pypi_0    pypi
alphashape                1.3.1                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
ca-certificates           2024.7.2             h06a4308_0    defaults
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
click-log                 0.4.0                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dash                      2.17.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
idna                      3.8                      pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
importlib-resources       6.4.4                    pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_1    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
nibabel                   5.2.1                    pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.20                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
openssl                   3.0.14               h5eee18b_0    defaults
packaging                 24.1                     pypi_0    pypi
panda                     0.3.1                    pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2             py38h06a4308_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.2.2                    pypi_0    pypi
plotly                    5.23.0                   pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyntcloud                 0.3.1                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
python                    3.8.19               h955ad1f_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
rtree                     1.3.0                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                72.1.0           py38h06a4308_0    defaults
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.13.2                   pypi_0    pypi
tenacity                  9.0.0                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0    defaults
torch                     2.4.0                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
trimesh                   4.4.7                    pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0    defaults
widgetsnbextension        4.0.13                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1    defaults
zipp                      3.20.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    defaults
